apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::{aws_account}:role/{project}-eks-cluster-nodes
      username: system:node:{{{{EC2PrivateDNSName}}}}
  {mapusers}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-10T17:33:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "414323"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 848c4c7e-78cb-48c2-bab2-d6b3d8a5639b