---
ports:
  web:
    port: 80
  websecure:
    port: 443

ingressRoute:
  dashboard:
    enabled: false # We will use a custom inrgessRoute with basic auth instead of the default one

## Enable HTTPS redirection on web entrypoint
additionalArguments:
#  - --entryPoints.web.http.redirections.entryPoint.to: websecure
#  - --entryPoints.web.http.redirections.entryPoint.scheme: https
  - "--entryPoints.web.address=:80/tcp"
  - "--entryPoints.web.forwardedHeaders.insecure"
  - "--entryPoints.websecure.address=:443/tcp"
  - "--entryPoints.websecure.forwardedHeaders.insecure"            
  - "--entrypoints.web.http.redirections.entryPoint.to=:443"
  - "--certificatesresolvers.aws.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
  - "--certificatesresolvers.aws.acme.dnsChallenge=true"
  - "--certificatesresolvers.aws.acme.dnsChallenge.provider=route53"
  - "--certificatesresolvers.aws.acme.email=roan@cloudopss.com.br"
  - "--certificatesresolvers.aws.acme.storage=/data/acme.json"
  - "--certificatesresolvers.aws.acme.dnschallenge.resolvers=8.8.8.8:53"

env:
  - name: AWS_ACCESS_KEY_ID
    value: AAAAAAAAAAAAAAAAAAAAA
  - name: AWS_SECRET_ACCESS_KEY
    value: BBBBBBBBBBBBBBBBBBBBBBBBBBBB
  - name: AWS_REGION
    value: us-east-2

persistence:
  enabled: true
  accessMode: "ReadWriteOnce"
  size: 1Gi

deployment:
  # Additional initContainers (e.g. for setting file permission as shown below)
  initContainers: # []
    # The "volume-permissions" init container is required if you run into permission issues.
    # Related issue: https://github.com/traefik/traefik/issues/6972
    - name: volume-permissions
      image: busybox:1.31.1
      command: ["sh", "-c", "chmod -Rv 600 /data/*"]
      volumeMounts:
      - name: data
        mountPath: /data

## The following lines are needed if you have an error like: error while building entryPoint web: error preparing server: error opening listener: listen tcp :80: bind: permission denied
## It just means that Traefik is unable to listen to connections on the host because of a lack of permissions.
## Hence the need for aditionnal permissions.
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0
