version: "3"

services:
  frontend:
    image: frontend:1.0
    container_name: frontend
    restart: on-failure
    #env_file: configs/frontend_develop.env
    ports:
      - 3000:3000
    networks:
      - mynet

  backend:
    image: backend:1.0
    container_name: backend
    restart: always
    #env_file: configs/backend_develop.env
    ports:
      - 5000:5000
    networks:
      - mynet

  nginx:
    image: nginx-reverse-proxy
    container_name: nginx
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynet

networks:
    mynet: